[env]
_.python.venv = { path = ".venv", create = true }
JUST_UNSTABLE = "1"

[settings]
experimental = true
pipx_uvx = true
python.uv_venv_auto = true

[tools]
python = "3.13" # Required for documentation generation
rust = "1.90.0" # Required for schematools
"aqua:astral-sh/uv" = "0.8.18"
"aqua:casey/just" = "1.42.4"
"aqua:google/yamlfmt" = "0.17.2"
"aqua:helm" = "3.19.0"
"aqua:helm/chart-testing" = "3.13.0"
"aqua:mikefarah/yq" = "4.47.2"
"cargo:schematools-cli" = "0.22.0"
"pipx:yamllint" = "1.37.1"
"pipx:yamale" = "6.0.0"

[hooks]
postinstall = "uv pip install --upgrade -r {{config_root}}/docs/requirements.txt"
